export const COLOR = {
  TEXT_COLOR: '#0B0C0C',
  SECONDARY_TEXT_COLOR: '#6F777B',
  PAGE_COLOR: '#FFFFFF',
  HEADER_ANDROID_COLOR: '#2B8CC4',
  POST_COLOR: '#F8F8F8',
  POST_BORDER_COLOR: '#BFC1C3',
};
